
name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    permissions:
      packages: write # For GHCR
      contents: read  # Not required for public repositories, but for clarity
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Login to ghcr.io registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: mms-gianni
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version
      id: bump_version
      run: | 
        export VERSION=$(echo ${{ github.ref }} | awk -F'/' '{print $3}')
        sed -i "s/DEV-VERSION/$VERSION/g" cmd/git-runner/main.go

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}